import assert from 'node:assert/strict';
import {aggregate,analyze,ratio} from '../lib/marketing.ts';
const ctx={channel:'전체 채널',period:'이번 주'};
const totals=aggregate(ctx);
assert.equal(totals.spend,42000000);
assert.equal(totals.revenue,151000000);
assert.equal(totals.conversions,3260);
assert.equal(totals.roas,151000000/42000000);
assert.equal(totals.cpa,42000000/3260);
assert.equal(ratio(4,0),null);
const report=analyze('이번 주 성과를 종합 분석해줘',ctx);
assert.equal(report.sections.length,4);
assert.equal(report.rows.length,4);
assert.match(report.sections[1].paragraphs[0],/1,500만원/);
assert.equal(-19000000-3000000+7000000,151000000-166000000);
assert.equal(45000*.032-900,540);
const meta=analyze('메타 구매 전환을 분석해줘',ctx);
assert.equal(meta.scope.channel,'Meta Ads');
assert.equal(meta.rows.length,1);
assert.match(meta.sections[1].paragraphs.join(' '),/540건/);
const kakao=analyze('카카오 성과 분석해줘',ctx);
assert.match(kakao.sections[1].paragraphs.join(' '),/43,750원에서 25,000원/);
const last=analyze('지난주 성과 분석해줘',ctx);
assert.equal(last.scope.period,'지난주');
assert.match(last.conclusion,/판단은 할 수 없습니다/);
assert.match(analyze('예산을 어떻게 조정해야 해?',ctx).sections[2].paragraphs.join(' '),/최적 예산 배분액/);
assert.equal(analyze('오늘 광고 성과 알려줘',ctx).rows.length,0);
assert.equal(analyze('메타 전환 분석해줘',{channel:'전체 채널',period:'지난주'}).scope.period,'지난주');
console.log('PASS: aggregate totals, revenue attribution, conversion arithmetic, report scope, budget and data limits');
