'use client';
import {useEffect,useRef,useState} from 'react';
import {Area,AreaChart,Bar,BarChart,CartesianGrid,XAxis,YAxis} from 'recharts';
import {Sparkles,Layers,LayoutDashboard,Target,FileText,ChevronRight,CalendarDays,SlidersHorizontal,PanelRightClose,Plus,Send,Expand,Copy,Check,Loader2,ArrowUpRight,ArrowDownRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {ChartContainer,ChartTooltip,ChartTooltipContent} from '@/components/ui/chart';
import {aggregate,analyze,channels,compact,delta,money,pct,type Analysis,type Context} from '@/lib/marketing';
type Message={role:'user'|'assistant';text:string;analysis?:Analysis};
const config={revenue:{label:'매출',color:'#4262D9'},previous:{label:'지난주 매출',color:'#BEC8E0'},roas:{label:'ROAS',color:'#4262D9'}};
function Trend({ctx}:{ctx:Context}){
 const now=aggregate(ctx),prev=aggregate({...ctx,period:'지난주'});
 const days=ctx.period==='이번 주'?['10/5','10/6','10/7','10/8','10/9','10/10','10/11']:['9/28','9/29','9/30','10/1','10/2','10/3','10/4'];
 const data=[.12,.15,.13,.16,.14,.17,.13].map((w,i)=>({day:days[i],revenue:Math.round(now.revenue*w/10000),previous:Math.round(prev.revenue*[.13,.14,.15,.13,.16,.14,.15][i]/10000)}));
 return <ChartContainer config={config} className="trend-chart"><AreaChart data={data} margin={{left:-8,right:10,top:16}} accessibilityLayer><defs><linearGradient id="revenue-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4262D9" stopOpacity={.22}/><stop offset="100%" stopColor="#4262D9" stopOpacity={.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0f6"/><XAxis dataKey="day" tickLine={false} axisLine={false} tickMargin={10}/><YAxis tickLine={false} axisLine={false} width={65} tickFormatter={v=>`${v.toLocaleString()}만`}/><ChartTooltip content={<ChartTooltipContent formatter={(v,n)=><span>{n==='previous'?'지난주 매출':'매출'} <b>{Number(v).toLocaleString()}만원</b></span>}/>} />{ctx.period==='이번 주'&&<Area type="monotone" dataKey="previous" stroke="#B9C4DB" strokeDasharray="4 5" fill="transparent" strokeWidth={2} isAnimationActive={false}/>}<Area type="monotone" dataKey="revenue" stroke="#4262D9" strokeWidth={3} fill="url(#revenue-fill)" isAnimationActive={false}/></AreaChart></ChartContainer>;
}
function ChannelChart({ctx}:{ctx:Context}){
 const data=channels.filter(c=>ctx.channel==='전체 채널'||c.name===ctx.channel).map(c=>{const r=ctx.period==='지난주'?c.previous:c;return {name:c.name,roas:Number((r.revenue/r.spend).toFixed(2))};});
 return <ChartContainer config={config} className="channel-chart"><BarChart data={data} layout="vertical" margin={{right:25,left:0,top:8,bottom:8}} accessibilityLayer><CartesianGrid horizontal={false} stroke="#edf0f6"/><XAxis type="number" axisLine={false} tickLine={false} unit="배"/><YAxis type="category" dataKey="name" width={90} axisLine={false} tickLine={false}/><ChartTooltip content={<ChartTooltipContent formatter={v=><span>ROAS <b>{Number(v).toFixed(2)}배</b></span>}/>} /><Bar dataKey="roas" fill="#4262D9" radius={[0,5,5,0]} barSize={20} isAnimationActive={false}/></BarChart></ChartContainer>;
}

function AnalysisAnswer({a}:{a:Analysis}){
 const [copied,setCopied]=useState(false),[error,setError]=useState(false);
 const copy=async()=>{try{await navigator.clipboard.writeText([a.title,a.conclusion,...a.sections.flatMap(s=>[s.title,...s.paragraphs]),a.closing].join('\n\n'));setCopied(true);setError(false);}catch{setError(true);}};
 return <article className="analysis-answer"><h2>{a.title}</h2><p className="analysis-scope">{a.scope.channel} · {a.scope.period==='이번 주'?'2026.10.05–10.11 / 09.28–10.04 비교':'2026.09.28–10.04'}</p><p className="analysis-lead">{a.conclusion}</p>{a.sections.map((s,i)=><section key={s.title}><h3>{s.title}</h3>{s.title==='추천 행동'?<ol className="answer-actions">{s.paragraphs.map((t,j)=><li key={j}>{t}</li>)}</ol>:s.paragraphs.map((t,j)=><p key={j}>{t}</p>)}{i===1&&a.rows.length>0&&<div className="analysis-table-scroll"><table className="analysis-table"><thead><tr><th>채널</th><th>매출 증감</th><th>ROAS</th><th>전환율</th></tr></thead><tbody>{a.rows.map(r=><tr key={r.name}><td>{r.name}</td><td>{r.change}</td><td>{r.roas}</td><td>{r.cvr}</td></tr>)}</tbody></table></div>}</section>)}{a.closing&&<p className="analysis-closing">{a.closing}</p>}<button className="copy-answer" onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'복사됨':'답변 복사'}</button>{error&&<p role="alert">복사할 수 없습니다. 답변 텍스트를 선택해서 복사해 주세요.</p>}</article>;
}
export default function Home(){
 const [ctx,setCtx]=useState<Context>({channel:'전체 채널',period:'이번 주'}),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(''),[open,setOpen]=useState(true),[wide,setWide]=useState(false),[busy,setBusy]=useState(false);
 const conversationScope=useRef(ctx),timer=useRef<ReturnType<typeof setTimeout>|null>(null),latest=useRef<HTMLDivElement>(null);
 useEffect(()=>{conversationScope.current=ctx;},[ctx]);
 useEffect(()=>{if(window.innerWidth<=760)setOpen(false);return()=>{if(timer.current)clearTimeout(timer.current);};},[]);
 useEffect(()=>{if(messages.length)latest.current?.scrollIntoView({behavior:'smooth',block:'start'});},[messages]);
 const ask=(q:string)=>{if(busy||!q.trim())return;setOpen(true);setInput('');setBusy(true);setMessages(m=>[...m,{role:'user',text:q}]);const a=analyze(q,conversationScope.current);conversationScope.current=a.scope;timer.current=setTimeout(()=>{setMessages(m=>[...m,{role:'assistant',text:a.conclusion,analysis:a}]);setBusy(false);},550);};
 const now=aggregate(ctx),prev=aggregate({...ctx,period:'지난주'}),compare=ctx.period==='이번 주';
 const metrics=[{label:'광고비',value:compact(now.spend),d:delta(now.spend,prev.spend),good:false},{label:'매출',value:compact(now.revenue),d:delta(now.revenue,prev.revenue),good:true},{label:'ROAS',value:`${(now.roas??0).toFixed(2)}배`,d:delta(now.roas??0,prev.roas??0),good:true},{label:'CPA',value:money(now.cpa??0),d:delta(now.cpa??0,prev.cpa??0),good:false}];
 return <main className={`workspace ${open?'chat-open':''} ${wide?'chat-wide':''}`}><aside className="nav-rail"><a className="brand" href="/"><span className="brand-icon"><Layers size={22}/></span><b>orbit<span>marketing</span></b></a><div className="workspace-name"><span className="workspace-avatar">M</span><div>마케팅 워크스페이스<small>Marketing workspace</small></div></div><nav><button className="nav-item active" onClick={()=>setOpen(false)}><LayoutDashboard/>성과 대시보드</button><button className="nav-item" onClick={()=>ask('채널별 성과를 종합 분석해줘')}><Target/>캠페인 분석</button><button className="nav-item" onClick={()=>ask('이번 주 마케팅 성과 보고서를 작성해줘')}><FileText/>성과 보고</button></nav><div className="nav-bottom"><div className="user-profile"><span>MK</span><div>마케팅 팀<small>Marketing team</small></div></div></div></aside><div className="main-area"><header className="topbar"><div className="breadcrumb">워크스페이스<ChevronRight size={14}/><b>성과 대시보드</b></div><div className="topbar-actions"><span className="demo-badge">샘플 데이터</span>{!open&&<Button size="sm" onClick={()=>setOpen(true)}><Sparkles/>AI 분석</Button>}</div></header>
<div className="dashboard-scroll"><div className="dashboard"><div className="dashboard-title"><div><div className="page-eyebrow">마케팅 성과</div><h1>성과 대시보드</h1><p>채널별 성과를 확인하고 다음 액션을 정하세요.</p></div><Button variant="outline" onClick={()=>ask('이번 주 마케팅 성과 보고서를 작성해줘')}><FileText/>성과 요약</Button></div><div className="filter-row"><div className="filter-controls"><label><CalendarDays size={15}/><select aria-label="분석 기간" value={ctx.period} onChange={e=>setCtx(c=>({...c,period:e.target.value}))}><option value="이번 주">10월 5일–11일</option><option value="지난주">9월 28일–10월 4일</option></select></label><label><SlidersHorizontal size={15}/><select aria-label="분석 채널" value={ctx.channel} onChange={e=>setCtx(c=>({...c,channel:e.target.value}))}><option>전체 채널</option>{channels.map(c=><option key={c.name}>{c.name}</option>)}</select></label></div><span className="comparison-label">{compare?'지난주 같은 기간 대비':'비교기간 데이터 없음'}</span></div><div className="metric-grid">{metrics.map(m=><div className="metric-card" key={m.label}><span>{m.label}</span><strong>{m.value}</strong><small className={!compare?'neutral':((m.d??0)>=0)===m.good?'positive':'negative'}>{compare?<>{(m.d??0)>=0?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>} {pct(m.d)} <em>지난주 대비</em></>:'지난주 집계'}</small></div>)}</div><section className="dashboard-panel"><div className="panel-heading"><div><h2>매출 추이</h2><span>{ctx.channel} · 일별 매출</span></div><div className="chart-legend"><span><i/>선택 기간</span>{compare&&<span><i className="previous"/>지난주</span>}</div></div><Trend ctx={ctx}/></section><div className="bottom-grid"><section className="dashboard-panel"><div className="panel-heading"><div><h2>채널별 광고 수익률</h2><span>매출 ÷ 광고비</span></div></div><ChannelChart ctx={ctx}/></section></div><section className="dashboard-panel table-panel"><div className="panel-heading"><div><h2>채널 성과</h2><span>광고 채널별 집계</span></div></div><div className="table-scroll"><table><thead><tr><th>채널</th><th>광고비</th><th>매출</th><th>ROAS</th><th>전환수</th><th>분석</th></tr></thead><tbody>{channels.filter(c=>ctx.channel==='전체 채널'||c.name===ctx.channel).map((c,i)=>{const r=ctx.period==='지난주'?c.previous:c;return <tr key={c.name}><td><span className={`channel-icon channel-${i}`}>{c.name[0]}</span>{c.name}</td><td>{compact(r.spend)}</td><td>{compact(r.revenue)}</td><td><b>{(r.revenue/r.spend).toFixed(2)}배</b></td><td>{r.conversions.toLocaleString()}</td><td><button aria-label={`${c.name} 분석`} onClick={()=>ask(`${c.name} 성과 분석해줘`)}><Sparkles size={15}/></button></td></tr>;})}</tbody></table></div></section><p className="dashboard-note">샘플 데이터 · 2026.10.05–10.11의 가상 실적</p></div></div>
</div>{open&&<aside className="assistant-panel"><header className="assistant-header"><div><span className="assistant-icon"><Sparkles size={19}/></span><div><b>Marketing Assistant</b><small>현재 성과를 분석하고 다음 행동을 제안합니다</small></div></div><div><Button variant="ghost" size="icon" aria-label={wide?'답변 너비 줄이기':'답변 넓게 보기'} onClick={()=>setWide(v=>!v)}><Expand/></Button><Button variant="ghost" size="icon" aria-label="새 대화" disabled={busy} onClick={()=>{setMessages([]);conversationScope.current=ctx;}}><Plus/></Button><Button variant="ghost" size="icon" aria-label="AI 분석 닫기" onClick={()=>setOpen(false)}><PanelRightClose/></Button></div></header><div className="context-strip"><span><Layers size={13}/>현재 화면 기준</span><small>{ctx.channel} · {ctx.period}</small></div><div className="chat-scroll" role="log" aria-label="분석 대화" aria-live="polite">{messages.length===0?<div className="chat-welcome"><span className="welcome-icon"><Sparkles size={28}/></span><h2>무엇을 점검할까요?</h2><p>현재 성과의 핵심 문제와 대응을 정리합니다.</p><div className="suggestion-list">{['이번 주 성과를 종합 분석해줘','매출 감소에 가장 큰 영향을 준 채널은?','예산을 어떻게 조정해야 해?'].map(q=><button key={q} onClick={()=>ask(q)}><span>{q}</span><ChevronRight/></button>)}</div></div>:messages.map((m,i)=><div key={i} ref={i===messages.length-1?latest:undefined} className={`chat-message ${m.role}`}>{m.role==='user'?<p>{m.text}</p>:<><div className="message-author"><Sparkles size={14}/><b>Marketing Assistant</b></div>{m.analysis&&<AnalysisAnswer a={m.analysis}/>}</>}</div>)}{busy&&<div className="thinking"><Loader2 size={16} className="spin"/>성과 변화와 채널별 영향을 정리하고 있어요…</div>}</div><form className="chat-composer" onSubmit={e=>{e.preventDefault();ask(input);}}><div className="composer-field"><textarea aria-label="마케팅 분석 질문" placeholder="성과와 다음 행동에 대해 물어보세요" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();ask(input);}}} rows={2} maxLength={2000}/><div className="composer-tools"><span>{ctx.channel} · {ctx.period}</span><Button size="icon" type="submit" disabled={busy||!input.trim()} aria-label="질문 보내기"><Send size={16}/></Button></div></div><p>샘플 데이터 기반 데모 · 실제 AI 미연결</p></form></aside>}</main>;
}
